import Drag from './components/common/Drag';
import * as util from './util';
import * as math from './math';
declare const _default: {
    components: {
        InputAngle: typeof import("./components/InputAngle.vue").default;
        InputButton: typeof import("./components/InputButton.vue").default;
        InputCodeEditor: typeof import("./components/InputCodeEditor").default;
        InputCheckbox: typeof import("./components/InputCheckbox.vue").default;
        InputColor: typeof import("./components/InputColor").default;
        InputColorButton: typeof import("./components/InputColorButton.vue").default;
        InputDropdown: typeof import("./components/InputDropdown.vue").default;
        InputIconAction: typeof import("./components/InputIconAction").default;
        InputIconButton: typeof import("./components/InputIconButton.vue").default;
        InputIconToggle: typeof import("./components/InputIconToggle.vue").default;
        InputMatrix: typeof import("./components/InputMatrix.vue").default;
        InputMode: typeof import("./components/InputMode.vue").default;
        InputNumber: typeof import("./components/InputNumber.vue").default;
        InputPoint: typeof import("./components/InputPoint.vue").default;
        InputRange: typeof import("./components/InputRange.vue").default;
        InputSlider: typeof import("./components/InputSlider.vue").default;
        InputString: typeof import("./components/InputString.vue").default;
        InputVector: typeof import("./components/InputVector.vue").default;
        ParamFieldAffine: typeof import("./components/ParamFieldAffine.vue").default;
        ParamFieldAngle: typeof import("./components/ParamFieldAngle.vue").default;
        ParamFieldColor: typeof import("./components/ParamFieldColor.vue").default;
        ParamFieldNumber: typeof import("./components/ParamFieldNumber.vue").default;
        ParamFieldPoint: typeof import("./components/ParamFieldPoint.vue").default;
        ParamFieldRange: typeof import("./components/ParamFieldRange.vue").default;
        ParamFieldSeed: typeof import("./components/ParamFieldSeed.vue").default;
        ParamFieldScale: typeof import("./components/ParamFieldScale.vue").default;
        ParamFieldSlider: typeof import("./components/ParamFieldSlider.vue").default;
    };
    common: {
        Drag: typeof Drag;
    };
    util: typeof util;
    math: typeof math;
};
export default _default;
